### PR TITLE
Bulkdata connectathon merge

### PR DESCRIPTION
**Pull request by bvdh**
I've merged my connectathon work with the bulk data support present in the master branch.
There are some areas where this code differs from the one in the master branch

1. I've separated the asynchronous processing from the $export functions on Patient and Group.
The asynchronous processing now works on all get operations. This creates the option to provide status updates for measure and plan definition processing. Killing processes when no longer needed. Something I would like to add in the future.

2. This version supports patientId based exports.

3. This version supports DELETE operations

4. A test class was added that tests the operation.

### CODE REVIEW

**Comment by c-schuler** [comment]
Thanks for the contributions Bas!

That's a lot of code and will take me some time to review and test everything. As a gentle suggestion: if you could issue smaller pull requests with a more singular focus in the future, that would be appreciated. 

My first concern is that you altered the code I had for bulk data $export to return a Bundle? That is not what the operation is supposed to return according to the documentation. Could you explain your reasoning behind that change?

**Comment by duncand** [comment]
I suggest that this pull request can still be replaced by multiple smaller pull requests if the author is willing.

**Comment by bvdh** [comment]
@duncand  Sure, What subdivision do you have in mind?

@c-schuler  I understand - I'll try to provide smaller updates from now on. 

Regarding why I changed the result of $export to a Bundle. 
This has to do with the split I made in the implementation. I've separated the asynchronous processing from the logic of doing the $export operation. So $export returns a set of resources - in a Bundle. The asynchronous processing code will take this and split it up if this is requested by the ndjson field.

**Comment by JPercival** [comment]
Closing because the PR is stale. Sorry this didn't ever get merged in. The base HAPI server now support bulk export. The cqf-ruler has not yet added support for async Measure eval.

**Pull request closed without merging**
